name: Deploy Vite App to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - shell: pwsh
        env:
          SUPER_SECRET: ${{ secrets.HUGGINGFACE_API_KEY }}
        run: |
          example-command "$env:SUPER_SECRET"